AWSTemplateFormatVersion: "2010-09-09"

Description: "Step Function for rotating Elasticsearch nodes"

Parameters:
  S3Bucket:
    Type: String
    Description: Bucket which contains .zip file used by lambda functions e.g. deploy-tools-dist
  S3Key:
    Type: String
    Description: Key for .zip file used by lambda functions e.g. <stack>/<stage>/elasticsearch-node-rotation/elasticsearch-node-rotation.zip
  AutoScalingGroupName:
    Type: String
    Description: The name of the auto-scaling group which contains the Elasticsearch nodes

Resources:

  NodeRotationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub NodeRotation
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - lambda.amazonaws.com
            Action:
            - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - lambda:InvokeFunction
                Resource: "*"
        - PolicyName: ElasticsearchAdminAsgPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                - autoscaling:DescribeAutoScalingGroups
                - ec2:DescribeInstances
                Resource: "*"
              - Effect: Allow
                Action:
                - autoscaling:SetDesiredCapacity
                - autoscaling:TerminateInstanceInAutoScalingGroup
                Resource: !Sub arn:aws:autoscaling:${AWS::Region}:${AWS::AccountId}:autoScalingGroup:*:autoScalingGroupName/${AutoScalingGroupName}
        - PolicyName: ElasticsearchAdminSsmPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                - ssm:SendCommand
                - ssm:GetCommandInvocation
                Resource: "*"

  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Principal:
            Service: !Sub states.${AWS::Region}.amazonaws.com
          Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                - lambda:InvokeFunction
                Resource: "*"

  ClusterStatusCheckLambda:
    Type: "AWS::Lambda::Function"
    DependsOn: NodeRotationLambdaRole
    Properties:
      FunctionName:
          !Sub enr-cluster-status-check
      Description: "Checks the status of an Elasticsearch cluster"
      Handler: "clusterStatusCheck.handler"
      Role: !GetAtt [ NodeRotationLambdaRole, Arn ]
      Code:
        S3Bucket: !Sub ${S3Bucket}
        S3Key: !Sub ${S3Key}
      MemorySize: 512
      Runtime: nodejs8.10
      Timeout: 300

  GetOldestNodeLambda:
    Type: "AWS::Lambda::Function"
    DependsOn: NodeRotationLambdaRole
    Properties:
      FunctionName:
          !Sub enr-get-oldest-node
      Description: "Finds the oldest node in an Elasticsearch cluster"
      Handler: "getOldestNode.handler"
      Role: !GetAtt [ NodeRotationLambdaRole, Arn ]
      Code:
        S3Bucket: !Sub ${S3Bucket}
        S3Key: !Sub ${S3Key}
      MemorySize: 512
      Runtime: nodejs8.10
      Timeout: 300
      Environment:
        Variables:
          ASG_NAME: !Sub ${AutoScalingGroupName}

  AddNodeLambda:
    Type: "AWS::Lambda::Function"
    DependsOn: NodeRotationLambdaRole
    Properties:
      FunctionName:
          !Sub enr-add-node
      Description: "Disables re-balancing before adding a new node into the Elasticsearch cluster"
      Handler: "addNode.handler"
      Role: !GetAtt [ NodeRotationLambdaRole, Arn ]
      Code:
        S3Bucket: !Sub ${S3Bucket}
        S3Key: !Sub ${S3Key}
      MemorySize: 512
      Runtime: nodejs8.10
      Timeout: 300
      Environment:
        Variables:
          ASG_NAME: !Sub ${AutoScalingGroupName}

  ClusterSizeCheckLambda:
    Type: "AWS::Lambda::Function"
    DependsOn: NodeRotationLambdaRole
    Properties:
      FunctionName:
          !Sub enr-cluster-size-check
      Description: "Confirms that the Elasticsearch cluster is the expected size"
      Handler: "clusterSizeCheck.handler"
      Role: !GetAtt [ NodeRotationLambdaRole, Arn ]
      Code:
        S3Bucket: !Sub ${S3Bucket}
        S3Key: !Sub ${S3Key}
      MemorySize: 512
      Runtime: nodejs8.10
      Timeout: 300
      Environment:
        Variables:
          ASG_NAME: !Sub ${AutoScalingGroupName}

  MigrateShardsLambda:
    Type: "AWS::Lambda::Function"
    DependsOn: NodeRotationLambdaRole
    Properties:
      FunctionName:
          !Sub enr-migrate-shards
      Description: "Migrates shards between two nodes"
      Handler: "migrateShards.handler"
      Role: !GetAtt [ NodeRotationLambdaRole, Arn ]
      Code:
        S3Bucket: !Sub ${S3Bucket}
        S3Key: !Sub ${S3Key}
      MemorySize: 512
      Runtime: nodejs8.10
      Timeout: 300

  NodeRotationStepFunction:
    Type: "AWS::StepFunctions::StateMachine"
    DependsOn:
    - GetOldestNodeLambda
    - ClusterStatusCheckLambda
    - AddNodeLambda
    - ClusterSizeCheckLambda
    - MigrateShardsLambda
    Properties:
      DefinitionString:
        !Sub
          - |
           {
             "Comment": "Elasticsearch Node Rotation",
             "StartAt": "GetOldestNode",
             "States": {
               "GetOldestNode": {
                 "Type": "Task",
                 "Resource": "${GetOldestNodeArn}",
                 "Next": "CheckClusterStatus"
               },
               "CheckClusterStatus": {
                 "Type": "Task",
                 "Resource": "${ClusterStatusCheckArn}",
                 "Next": "StatusIsGreen"
               },
               "StatusIsGreen": {
                 "Type": "Choice",
                 "Choices": [
                   {
                     "Not": {
                       "Variable": "$.clusterStatus",
                       "StringEquals": "green"
                     },
                     "Next": "FailState"
                   }
                 ],
                 "Default": "AddNode"
               },
               "FailState": {
                 "Type": "Fail",
                 "Cause": "Unhealthy Cluster!"
               },
               "AddNode": {
                 "Type": "Task",
                 "Resource": "${AddNodeArn}",
                 "Next": "ClusterSizeCheck"
               },
               "ClusterSizeCheck": {
                 "Type": "Task",
                 "Resource": "${ClusterSizeCheckArn}",
                 "Next": "MigrateShards",
                 "Retry": [ {
                   "ErrorEquals": [ "States.ALL" ],
                   "IntervalSeconds": 10,
                   "MaxAttempts": 12
                  } ]
               },
               "MigrateShards": {
                  "Type": "Task",
                  "Resource": "${MigrateShardsArn}",
                  "End": true
               }
             }
           }
          -
            GetOldestNodeArn: !GetAtt GetOldestNodeLambda.Arn
            ClusterStatusCheckArn: !GetAtt ClusterStatusCheckLambda.Arn
            AddNodeArn: !GetAtt AddNodeLambda.Arn
            ClusterSizeCheckArn: !GetAtt ClusterSizeCheckLambda.Arn
            MigrateShardsArn: !GetAtt MigrateShardsLambda.Arn
      RoleArn: !GetAtt StatesExecutionRole.Arn
